### ISSUE TITLE
About the dataset.

### ISSUE THREAD

**Issue by liuyijiang1994** [KisuYang/EmotionX-KU#1]
Hi, congratulations !
I have a question about where i can get the test set.
I only have the original dataset and a test set without emotion label for emotionX2019.
Thanks!

**Comment by KisuYang** [comment]
Thank you for your interest !
I got the labeled test dataset from the administrator as participating in the shared task.
It would be better to contact him via the official webpage, https://sites.google.com/view/emotionx2019/people.
Thanks!

**Comment by liuyijiang1994** [comment]
Thank you for your answer, it helps me a lot!

**Comment by liuyijiang1994** [comment]
Hey Kisu @KisuYang , 
Sorry to bother you again, I sent an email to the organizers but received the test dataset of the emotionX2018, I guess they made some mistakes but I don't receive anything more. Could you send a copy of the test dataset to me please?
Thanks!

**Comment by KisuYang** [comment]
Sorry, I do not have any rights to release the dataset. How about re-asking them to the 2019 labeled golden testsets if you received the 2018 version due to their mistakes?

**Comment by KisuYang** [comment]
Sorry, I do not have any rights to release the dataset. How about re-asking them to the 2019 labeled golden testsets if you received the 2018 version due to their mistakes?

**Comment by liuyijiang1994** [comment]
@KisuYang Maybe that's the only way, whatever thanks for your help!
